name: "Publish"
on:
  push:
   branches:
      - master
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: srid
    - name: Download neuron
      run: |
        #curl --silent https://api.github.com/repos/srid/neuron/actions/artifacts \
        #  | jq 'first(.artifacts | .[] | select(.name == "neuron-bundle-linux") | .archive_download_url)' -r \
        #  | xargs curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --silent -L -o neuron-bundle-linux.zip
        #unzip neuron-bundle-linux.zip
        #chmod +x neuron
        #./neuron --version  # This extracts the bundle; should take a while
        nix-env -if https://github.com/srid/neuron/archive/master.tar.gz
    - name: Build neuron site ðŸ”§
      run: |
        neuron gen
    - name: Deploy to gh-pages ðŸš€
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .neuron/output/
